### ISSUE TITLE
Crash when a gift sub is given.

### ISSUE THREAD

**Issue by tisboyo** [tisboyo/Twitch_Bot#222]
```
twitchbot_bot           | Publishing ka1os has Subscribed to the channel to MQTT
twitchbot_bot           | streamlabs(baldengineer): $ Ka1os just gifted 1 Tier 1 subscriptions!
twitchbot_bot           | Publishing ka1os has Subscribed to the channel to MQTT
twitchbot_bot           |
twitchbot_bot           | error has occurred while triggering a event on a mod, details:
twitchbot_bot           | mod: twitchlog
twitchbot_bot           | event: Event.on_pubsub_subscription
twitchbot_bot           | error: <class 'sqlalchemy.exc.IntegrityError'>
twitchbot_bot           | reason: (mysql.connector.errors.IntegrityError) 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`twitchbot`.`subscriptions`, CONSTRAINT `subscriptions_ibfk_2` FOREIGN KEY (`user_
id`) REFERENCES `users` (`user_id`))
twitchbot_bot           | [SQL: INSERT INTO subscriptions (user_id, channel, subscription_level, cumulative_months, streak_months) VALUES (%(user_id)s, %(channel)s, %(subscription_level)s, %(cumulative_months)s, %(streak_months)s)]
twitchbot_bot           | [parameters: {'user_id': '187277776', 'channel': '125957551', 'subscription_level': '1000', 'cumulative_months': 0, 'streak_months': 0}]
twitchbot_bot           | (Background on this error at: http://sqlalche.me/e/14/gkpj)
twitchbot_bot           | stack trace:
twitchbot_bot           | Traceback (most recent call last):
twitchbot_bot           |   File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 506, in cmd_query
twitchbot_bot           |     self._cmysql.query(query,
twitchbot_bot           | _mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`twitchbot`.`subscriptions`, CONSTRAINT `subscriptions_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` 
(`user_id`))
twitchbot_bot           |
twitchbot_bot           | During handling of the above exception, another exception occurred:
twitchbot_bot           |
twitchbot_bot           | Traceback (most recent call last):
twitchbot_bot           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
twitchbot_bot           |     self.dialect.do_execute(
twitchbot_bot           |   File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
twitchbot_bot           |     cursor.execute(statement, parameters)
twitchbot_bot           |   File "/usr/local/lib/python3.9/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
twitchbot_bot           |     result = self._cnx.cmd_query(stmt, raw=self._raw,
twitchbot_bot           |   File "/usr/local/lib/python3.9/site-packages/mysql/connector/connection_cext.py", line 510, in cmd_query
twitchbot_bot           |     raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
twitchbot_bot           | mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`twitchbot`.`subscriptions`, CONSTRAINT `subscriptions_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`))

```

**Comment by tisboyo** [comment]
Not quite fixed yet.

**Comment by tisboyo** [comment]
Going to leave this open for now, fa3b74a may have fixed this by committing to the database before the next event, which is the users sub event, comes in and the routine runs again. 

Just going to have to wait for another gift sub to happen to catch the error.

**Comment by tisboyo** [comment]
On further research, looks like this is happening when the recipient is not in the Users table.

**Comment by tisboyo** [comment]
Testing shows the user being in the database does not generate an error now. Still going to leave this open to see if we can catch it crash again.
